### ISSUE TITLE
TypeError: path must not be empty

### ISSUE THREAD

**Issue by ghost** [everdimension/physical-link#4]
### 1
physical-link --config D:\OneDrive\Documents\Repository\js\physical-link\physical-link.config.cjs --project .       
Watching dependencies:
  cute-openai
  cute-utilnode:fs:581
  return binding.open(
                 ^

Error: C:\Users\SDS\WebstormProjects\SmartDocNotes\UsersSDSWebstormProjectscute-openai\package.json: ENOENT: no such file or directory, open 'C:\Users\SDS\WebstormProjects\SmartDocNotes\UsersSDSWebstormProjectscute-openai\package.json'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at Object.readFileSync (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\jsonfile\index.js:50:22)
    at physicalLink (file:///C:/Users/SDS/AppData/Roaming/npm/node_modules/physical-link/src/index.js:96:31)
    at file:///C:/Users/SDS/AppData/Roaming/npm/node_modules/physical-link/src/cli.js:17:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\SDS\\WebstormProjects\\SmartDocNotes\\UsersSDSWebstormProjectscute-openai\\package.json'
}

Node.js v20.11.0

this is my config
```

module.exports = {
  manifest: {
    "cute-openai": "C:\Users\SDS\WebstormProjects\cute-openai",
	"cute-util": "C:\Users\SDS\WebstormProjects\cute-util",
  },
};
```

**_edit: okay so i guess you need  forward slashes? thats a pain._**

but now

### 2

 physical-link --config D:\OneDrive\Documents\Repository\js\physical-link\physical-link.config.cjs --project .
Watching dependencies:
  cute-openai
  cute-utilC:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\ignore\index.js:387
  throw new Ctor(message)
        ^

TypeError: path must not be empty
    at throwError (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\ignore\index.js:387:9)
    at checkPath (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\ignore\index.js:400:12)
    at Ignore._test (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\ignore\index.js:527:5)
    at Ignore.ignores (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\ignore\index.js:572:17)
    at ignored (file:///C:/Users/SDS/AppData/Roaming/npm/node_modules/physical-link/src/index.js:127:16)
    at matchPatterns (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\anymatch\index.js:62:18)
    at FSWatcher._userIgnored (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\anymatch\index.js:96:14)
    at FSWatcher._isIgnored (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\chokidar\index.js:779:15)
    at NodeFsHandler._addToNodeFs (C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\chokidar\lib\nodefs-handler.js:589:16)
    at C:\Users\SDS\AppData\Roaming\npm\node_modules\physical-link\node_modules\chokidar\index.js:451:47

Node.js v20.11.0

**what must not be empty?**

**Comment by ghost** [comment]
bro this kind of a mess

**Comment by everdimension** [comment]
It looks like maybe the `package.json` file is missing in your `UsersSDSWebstormProjectscute-openai` directory. Can you please verify it's there?

**Comment by ghost** [comment]
![Screenshot 2024-02-15 182154](https://github.com/everdimension/physical-link/assets/100174069/7bb679ba-4141-4845-843a-d030d00296dc)
It's there for sure. but is that path supposed to be missing the slashes?

**Comment by ghost** [comment]
idk i tried inputting the path in different variations and different slashes and in different places but it stopped working completely. cant link anything anywhere even if the config is local
